export const PERMISSIONS = {
  // Tenant management
  TENANT_CREATE: 'tenant.create',
  TENANT_UPDATE: 'tenant.update',
  TENANT_DELETE: 'tenant.delete',
  
  // Member management
  MEMBER_INVITE: 'member.invite',
  MEMBER_MANAGE: 'member.manage',
  MEMBER_VIEW: 'member.view',
  
  // Role management
  ROLE_VIEW: 'role.view',
  ROLE_MANAGE: 'role.manage',
  
  // Audit logs
  AUDIT_VIEW: 'audit.view',
  
  // API keys
  APIKEY_CREATE: 'apikey.create',
  APIKEY_VIEW: 'apikey.view',
  APIKEY_REVOKE: 'apikey.revoke',
  
  // Profile
  PROFILE_VIEW: 'profile.view',
  PROFILE_UPDATE: 'profile.update',
  
  // Dashboard
  DASHBOARD_VIEW: 'dashboard.view',
  DASHBOARD_SETTINGS_UPDATE: 'dashboard.settings.update',
} as const;

export type PermissionKey = typeof PERMISSIONS[keyof typeof PERMISSIONS];

export const DEFAULT_ROLES = {
  OWNER: 'Owner',
  ADMIN: 'Admin',
  MEMBER: 'Member',
  VIEWER: 'Viewer',
} as const;

export const ROLE_PERMISSIONS = {
  [DEFAULT_ROLES.OWNER]: [
    PERMISSIONS.TENANT_CREATE,
    PERMISSIONS.TENANT_UPDATE,
    PERMISSIONS.TENANT_DELETE,
    PERMISSIONS.MEMBER_INVITE,
    PERMISSIONS.MEMBER_MANAGE,
    PERMISSIONS.MEMBER_VIEW,
    PERMISSIONS.ROLE_VIEW,
    PERMISSIONS.ROLE_MANAGE,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.APIKEY_CREATE,
    PERMISSIONS.APIKEY_VIEW,
    PERMISSIONS.APIKEY_REVOKE,
    PERMISSIONS.PROFILE_VIEW,
    PERMISSIONS.PROFILE_UPDATE,
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DASHBOARD_SETTINGS_UPDATE,
  ],
  [DEFAULT_ROLES.ADMIN]: [
    PERMISSIONS.TENANT_UPDATE,
    PERMISSIONS.MEMBER_INVITE,
    PERMISSIONS.MEMBER_MANAGE,
    PERMISSIONS.MEMBER_VIEW,
    PERMISSIONS.ROLE_VIEW,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.APIKEY_CREATE,
    PERMISSIONS.APIKEY_VIEW,
    PERMISSIONS.APIKEY_REVOKE,
    PERMISSIONS.PROFILE_VIEW,
    PERMISSIONS.PROFILE_UPDATE,
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DASHBOARD_SETTINGS_UPDATE,
  ],
  [DEFAULT_ROLES.MEMBER]: [
    PERMISSIONS.MEMBER_VIEW,
    PERMISSIONS.PROFILE_VIEW,
    PERMISSIONS.PROFILE_UPDATE,
    PERMISSIONS.DASHBOARD_VIEW,
  ],
  [DEFAULT_ROLES.VIEWER]: [
    PERMISSIONS.MEMBER_VIEW,
    PERMISSIONS.PROFILE_VIEW,
    PERMISSIONS.PROFILE_UPDATE,
    PERMISSIONS.DASHBOARD_VIEW,
  ],
} as const;
